version: "2"
services:
  mysql:
    image: 'mysql:5.6.35'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: docker
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - 3333:3306
  php:
    build: docker/dockerfiles/php/
    image: php:7.0-fpm
    links: 
      - mysql:mysqldb
    volumes: 
      - ./www/:/var/www/html
  apache: 
    build: docker/dockerfiles/apache/
    links: 
      - php:phpfpm
    volumes: 
      - ./www/:/var/www/html
    ports:
      - 8889:80

# docker volume create --name pgdata-volume -d local
  dbpostgres:
    restart: always
    image: postgres:10.0
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata-volume:
    external: true